name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run
        working-directory: build
        run: ctest --output-on-failure

  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure
        run: cmake -S examples -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run
        run: cmake --build build --target run
